pipeline:
  build:
    image: plugins/docker
    repo: kradalby/dfektlan.no
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: dfektlan-deployment
    repo: kradalby/dfektlan.no
    container: dfektlan-container
    namespace: default
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
